# Generated by Django 3.1 on 2021-02-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
        ('users', '0003_auto_20210204_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='profil.profil'),
        ),
    ]
