# Generated by Django 3.1 on 2021-02-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilSortie', '0001_initial'),
        ('users', '0004_user_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profilSortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='profilSortie.profilsortie'),
        ),
    ]
