# Generated by Django 3.1 on 2021-02-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilSortie', '0001_initial'),
        ('users', '0005_student_profilsortie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profilSortie',
        ),
        migrations.AddField(
            model_name='student',
            name='profilSortie',
            field=models.ManyToManyField(related_name='students_profilSortie', to='profilSortie.ProfilSortie'),
        ),
    ]
