# Generated by Django 3.1 on 2021-02-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupeCompetence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('groupeCompetence', models.ManyToManyField(blank=True, related_name='competences', to='groupeCompetence.GroupeCompetence')),
            ],
        ),
        migrations.CreateModel(
            name='Niveaux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupeAction', models.CharField(max_length=200)),
                ('critereEvaluation', models.CharField(max_length=200)),
                ('niveaux', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='competence.competence')),
            ],
        ),
    ]
