# Generated by Django 3.1 on 2021-02-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20210204_2258'),
        ('referentiels', '0002_auto_20210205_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('lieu', models.CharField(max_length=200)),
                ('referenceAgate', models.CharField(max_length=200, null=True)),
                ('dateDebut', models.DateField()),
                ('dateFinProvisoire', models.DateField()),
                ('dateFinReelle', models.DateField()),
                ('fabrique', models.CharField(default='SONATEL ACADEMY', max_length=200)),
                ('etat', models.CharField(max_length=200, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin')),
                ('formateurs', models.ManyToManyField(related_name='promo', to='users.Teacher')),
                ('referentiels', models.ManyToManyField(related_name='promo', to='referentiels.Referentiel')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('dateCreation', models.DateField(auto_now=True)),
                ('statut', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('apprenant', models.ManyToManyField(related_name='groupe', to='users.Student')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo.promo')),
            ],
        ),
    ]
