# Generated by Django 3.1 on 2021-02-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='statut',
            field=models.CharField(default='Dispo', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='dateFinReelle',
            field=models.DateField(null=True),
        ),
    ]
