# Generated by Django 3.1 on 2021-02-05 16:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('presentation', models.CharField(max_length=200)),
                ('critereAdmission', models.CharField(max_length=200)),
                ('critereEvaluation', models.CharField(max_length=200)),
                ('programme', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/doc'), upload_to='')),
            ],
        ),
    ]
