# Generated by Django 3.1 on 2021-02-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentiel',
            name='programme',
            field=models.FileField(blank=True, default=None, null=True, upload_to='doc/'),
        ),
    ]
